// Code generated by hertz generator.

package cart

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	cart "github.com/jichenssg/tikmall/app/gateway/biz/model/frontend/cart"
	common "github.com/jichenssg/tikmall/app/gateway/biz/model/frontend/common"
)

// AddItem .
// @router /cart [POST]
func AddItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.AddItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.Response)

	c.JSON(consts.StatusOK, resp)
}

// GetCart .
// @router /cart [GET]
func GetCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.GetCartReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cart.GetCartResp)

	c.JSON(consts.StatusOK, resp)
}

// EmptyCart .
// @router /cart/empty [POST]
func EmptyCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.EmptyCartReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.Response)

	c.JSON(consts.StatusOK, resp)
}
