services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"     # Consul Web UI
      - "8600:8600"
    command: agent -dev -client=0.0.0.0 -ui
    networks:
      - tikmall

networks:
  tikmall:
    driver: bridge
