services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"     # Consul Web UI
      - "8600:8600"
    command: agent -dev -client=0.0.0.0 -ui
    networks:
      - tikmall
  jaeger:
    image: jaegertracing/all-in-one:1.58.0
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 16686:16686
      - 4317:4317   # grpc collector
      - 4318:4318   # http collector
    networks:
      - tikmall

networks:
  tikmall:
    driver: bridge
