services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./env/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - tikmall
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - tikmall
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"     # Consul Web UI
      - "8600:8600"
    command: agent -dev -client=0.0.0.0 -ui
    networks:
      - tikmall
  jaeger:
    image: jaegertracing/all-in-one:1.58.0
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 16686:16686
      - 4317:4317   # grpc collector
      - 4318:4318   # http collector
    networks:
      - tikmall
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./env/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "8090:9090"
    networks:
      - tikmall
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - tikmall

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    container_name: kafka1
    ports:
      - "19092:19092"
      - "19093:19093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      CLUSTER_ID: LelM2dIFQkiUFvXCEcqRWA
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092,CONTROLLER://0.0.0.0:19093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:19093,2@kafka2:29093,3@kafka3:39093"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_FORMAT_STORAGE: true
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: false
    networks:
      - tikmall

  kafka2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka2
    container_name: kafka2
    ports:
      - "29092:29092"
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      CLUSTER_ID: LelM2dIFQkiUFvXCEcqRWA
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:19093,2@kafka2:29093,3@kafka3:39093"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_FORMAT_STORAGE: true
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: false
    networks:
      - tikmall

  kafka3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka3
    container_name: kafka3
    ports:
      - "39092:39092"
      - "39093:39093"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_NODE_ID: 3
      CLUSTER_ID: LelM2dIFQkiUFvXCEcqRWA
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:39092,CONTROLLER://0.0.0.0:39093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:39092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:19093,2@kafka2:29093,3@kafka3:39093"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_FORMAT_STORAGE: true
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: false
    networks:
      - tikmall

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 7080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "TRUE"
    networks:
      - tikmall
  # loki:
  #   image: grafana/loki:2.9.2
  #   volumes:
  #     - ./env/config/loki.yml:/etc/loki/local-config.yaml
  #   command: -config.file=/etc/loki/local-config.yaml
  #   ports:
  #     - "3100:3100"
  #   networks:
  #     - tikmall
  # promtail:
  #   image: grafana/promtail:2.9.2
  #   volumes:
  #     - ./env/config/promtail.yml:/etc/promtail/config.yml
  #     - ./app/frontend/log:/logs/frontend
  #   command: -config.file=/etc/promtail/config.yml
  #   networks:
  #     - tikmall

networks:
  tikmall:
    driver: bridge
