// Code generated by hertz generator.

package product

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categorycreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categorydeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categorylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoryupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productgetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productsearchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}
