// Code generated by hertz generator.

package main

import (
	"fmt"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/kitex/pkg/klog"
	"github.com/jichenssg/tikmall/app/common/obs"
	"github.com/jichenssg/tikmall/gateway/config"
	"github.com/natefinch/lumberjack"
)

func main() {
	config.GetConf()

	obs.InitLog(&lumberjack.Logger{
		Filename:   config.GetConf().Kitex.LogFileName,
		MaxSize:    config.GetConf().Kitex.LogMaxSize,
		MaxBackups: config.GetConf().Kitex.LogMaxBackups,
		MaxAge:     config.GetConf().Kitex.LogMaxAge,
	}, config.LogLevel())

	klog.Info("Starting gateway server...")

	obs.InitTrack(config.GetConf().Server.Name, fmt.Sprintf("%v:%v", config.GetConf().Telemetry.Host, config.GetConf().Telemetry.Port))

	hertzInit()
}

func hertzInit() {
	h := server.New(
		server.WithHostPorts(fmt.Sprintf(":%v", config.GetConf().Server.Port)),
	)

	register(h)
	h.Spin()
}
