// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/pkg/klog"
	common "github.com/jichenssg/tikmall/gateway/biz/model/frontend/common"
	user "github.com/jichenssg/tikmall/gateway/biz/model/frontend/user"
	"github.com/jichenssg/tikmall/gateway/client"
	"github.com/jichenssg/tikmall/gen/kitex_gen/auth"
)

// Register .
// @router /auth/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.Response)

	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &user.LoginResp{
			Message: err.Error(),
		})

		return
	}

	authc, err := client.GetAuthClient()
	if err != nil {
		klog.CtxErrorf(ctx, "fail to get auth client", err)
		c.JSON(consts.StatusInternalServerError, &user.LoginResp{
			Message: err.Error(),
		})

		return
	}

	resp, err := authc.VerifyTokenByRPC(ctx, &auth.VerifyTokenReq{
		Token: "123",
	})

	if err != nil {
		klog.CtxErrorf(ctx, "fail to verify token by rpc", err)
		c.JSON(consts.StatusInternalServerError, &user.LoginResp{
			Message: err.Error(),
		})

		return
	}

	if !resp.Res {
		c.JSON(consts.StatusUnauthorized, &user.LoginResp{
			Message: "login failed",
		})

		return
	}

	c.JSON(consts.StatusOK, &user.LoginResp{
		Message: "login success",

	})
}

// Logout .
// @router /auth/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req common.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.Response)

	c.JSON(consts.StatusOK, resp)
}
