server:
  host: 172.16.53.189
  port: 9000
  name: auth
consul:
  host: 127.0.0.1
  port: 8500
kitex:
  log_level: debug
  log_file_name: "log/kitex.log"
  log_max_size: 10
  log_max_age: 3
  log_max_backups: 50
telemetry:
  host: 127.0.0.1
  port: 4317
metrics:
  port: 10000
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password: ""
token:
  access_expire: 25920000 # access token expire time
  refresh_expire: 2592000 # refresh token expire time